#!/bin/bash
make
 printf "\n test 1: \n"
./Comments3 < test1.txt
 printf "\n test 2: \n"
./Comments3 < test2.txt
 printf "\n test 3: \n"
./Comments3 < test3.txt
 printf "\n test 4: \n"
./Comments3 < test4.txt
 printf "\n test 5: \n"
./Comments3 < test5.txt
 printf "\n test 6: \n"
./Comments3 < test6.txt
 printf "\n test 7: \n"
./Comments3 < test7.txt
 printf "\n test 8: \n"
./Comments3 < test8.txt
 printf "\n test 9: \n"
./Comments3 < test9.txt
 printf "\n test 10: \n"
./Comments3 < test10.txt
 printf "\n test 11: \n"
./Comments3 < test11.txt
 printf "\n test 12: \n"
./Comments3 < test12.txt
